// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToysAndGames.DataAccess;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ToysAndGamesContext))]
    [Migration("20220617224822_ChangedFromDataAnnotationsToFluentAPI")]
    partial class ChangedFromDataAnnotationsToFluentAPI
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToysAndGames.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mattel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hasbro"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mi Alegria"
                        });
                });

            modelBuilder.Entity("ToysAndGames.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 3,
                            CompanyId = 1,
                            Description = "Twin Mill",
                            Name = "Hot Wheels",
                            Price = 25m
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 5,
                            CompanyId = 2,
                            Name = "Monopoly",
                            Price = 220.5m
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            Name = "Maquina de Raspados",
                            Price = 620.35m
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 3,
                            CompanyId = 1,
                            Description = "Twin Mill 2",
                            Name = "Hot Wheels",
                            Price = 25.88m
                        });
                });

            modelBuilder.Entity("ToysAndGames.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "Images\\TwinMill.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "Images\\Monopoly.jfif",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "Images\\maquinaderaspados.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "Images\\TwinMill2.jpg",
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("ToysAndGames.Models.Product", b =>
                {
                    b.HasOne("ToysAndGames.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ToysAndGames.Models.ProductImage", b =>
                {
                    b.HasOne("ToysAndGames.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ToysAndGames.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
