// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToysAndGames.DataAccess;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ToysAndGamesContext))]
    partial class ToysAndGamesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToysAndGames.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Name = "Mattel"
                        },
                        new
                        {
                            CompanyId = 2,
                            Name = "Hasbro"
                        },
                        new
                        {
                            CompanyId = 3,
                            Name = "Mi Alegria"
                        });
                });

            modelBuilder.Entity("ToysAndGames.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int?>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("Money");

                    b.HasKey("ProductId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AgeRestriction = 3,
                            CompanyId = 1,
                            Description = "Twin Mill",
                            Name = "Hot Wheels",
                            Price = 25m
                        },
                        new
                        {
                            ProductId = 2,
                            AgeRestriction = 5,
                            CompanyId = 2,
                            Name = "Monopoly",
                            Price = 220.5m
                        },
                        new
                        {
                            ProductId = 3,
                            CompanyId = 3,
                            Name = "Maquina de Raspados",
                            Price = 620.35m
                        },
                        new
                        {
                            ProductId = 4,
                            AgeRestriction = 3,
                            CompanyId = 1,
                            Description = "Twin Mill 2",
                            Name = "Hot Wheels",
                            Price = 25.88m
                        });
                });

            modelBuilder.Entity("ToysAndGames.Models.Product", b =>
                {
                    b.HasOne("ToysAndGames.Models.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ToysAndGames.Models.Company", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
